# Generated by Django 4.2.6 on 2023-10-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
